import React, { useState, useEffect } from 'react';
import './RecipePage.css';
import SearchBar from './SearchBar';
import FilterRecipes from './FilterRecipes';
import RecipeList from './RecipeList';
import RecipeReview from './RecipeReview'; // Import the RecipeReview component

const allRecipes = [
  {
    id: 1,
    title: 'Spaghetti Carbonara',
    description: 'A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.',
    image: 'https://cdn.pixabay.com/photo/2011/04/29/11/22/spaghetti-7115_1280.jpg',
    vegetarian: false,
    vegan: false,
    lowCarb: false,
    glutenFree: false,
    lactoseFree: false,
    nutFree: true,
    soyFree: true,
    eggFree: true,
  },
  {
    id: 2,
    title: 'Caprese Salad',
    description: 'Fresh mozzarella, tomatoes, basil, and a drizzle of olive oil and balsamic vinegar.',
    image: 'https://media.istockphoto.com/id/1345888788/photo/caprese-salad.webp?s=2048x2048&w=is&k=20&c=-32fLOWVCRAcSptqBkUtwcmeasztpqrDqvzU14nhhL0=',
    vegetarian: true,
    vegan: false,
    lowCarb: true,
    glutenFree: true,
    lactoseFree: false,
    nutFree: true,
    soyFree: true,
    eggFree: true,
  },
  {
    id: 3,
    title: 'Chicken Tikka Masala',
    description: 'Tender pieces of chicken in a spiced tomato gravy, served with rice or naan.',
    image: 'https://media.istockphoto.com/id/967274038/photo/homemade-chicken-tikka-masala.webp?s=2048x2048&w=is&k=20&c=CNG4IyE4nwTWR_uspYKIyAzBFz1MvObxhmolOpodR7E=',
    vegetarian: false,
    vegan: false,
    lowCarb: false,
    glutenFree: false,
    lactoseFree: false,
    nutFree: true,
    soyFree: true,
    eggFree: false,
  },
  {
    id: 4,
    title: 'Beef Stir-fry',
    description: 'Quick and easy stir-fry with thinly sliced beef, bell peppers, and broccoli.',
    image: 'https://cdn.pixabay.com/photo/2019/09/05/01/08/food-4452838_1280.jpg',
    vegetarian: false,
    vegan: false,
    lowCarb: true,
    glutenFree: false,
    lactoseFree: true,
    nutFree: true,
    soyFree: false,
    eggFree: true,
  },
  {
    id: 5,
    title: 'Vegetable Curry',
    description: 'A rich and flavorful curry with mixed vegetables and a blend of spices.',
    image: 'https://cdn.pixabay.com/photo/2021/06/10/02/31/rice-6324799_1280.jpg',
    vegetarian: true,
    vegan: true,
    lowCarb: false,
    glutenFree: true,
    lactoseFree: true,
    nutFree: true,
    soyFree: true,
    eggFree: true,
  },
  {
    id: 6,
    title: 'Chocolate Chip Cookies',
    description: 'Classic cookies loaded with chocolate chips, perfect for any time of day.',
    image: 'https://cdn.pixabay.com/photo/2023/06/22/22/29/cookies-8082386_1280.jpg',
    vegetarian: true,
    vegan: false,
    lowCarb: false,
    glutenFree: false,
    lactoseFree: false,
    nutFree: false,
    soyFree: true,
    eggFree: false,
  },
  // New recipes begin here
  {
    id: 7,
    title: 'Vegetable Stir-fry',
    description: 'A colorful mix of vegetables stir-fried with soy sauce and garlic.',
    image: 'https://cdn.pixabay.com/photo/2016/11/19/17/13/stir-fry-1847962_1280.jpg',
    vegetarian: true,
    vegan: true,
    lowCarb: true,
    glutenFree: true,
    lactoseFree: true,
    nutFree: true,
    soyFree: true,
    eggFree: true,
  },
  {
    id: 8,
    title: 'Greek Salad',
    description: 'A refreshing salad with cucumbers, tomatoes, olives, feta cheese, and olive oil.',
    image: 'https://cdn.pixabay.com/photo/2020/06/29/18/36/salad-3480517_1280.jpg',
    vegetarian: true,
    vegan: false,
    lowCarb: true,
    glutenFree: true,
    lactoseFree: false,
    nutFree: true,
    soyFree: true,
    eggFree: true,
  },
  {
    id: 9,
    title: 'Shrimp Tacos',
    description: 'Flaky shrimp wrapped in corn tortillas with cabbage and lime crema.',
    image: 'https://cdn.pixabay.com/photo/2020/07/25/18/48/tacos-5515481_1280.jpg',
    vegetarian: false,
    vegan: false,
    lowCarb: true,
    glutenFree: false,
    lactoseFree: false,
    nutFree: true,
    soyFree: true,
    eggFree: false,
  },
  {
    id: 10,
    title: 'Lentil Soup',
    description: 'A hearty soup made with lentils, vegetables, and herbs.',
    image: 'https://cdn.pixabay.com/photo/2017/01/06/16/29/lentil-1950276_1280.jpg',
    vegetarian: true,
    vegan: true,
    lowCarb: false,
    glutenFree: true,
    lactoseFree: true,
    nutFree: true,
    soyFree: true,
    eggFree: true,
  },
  {
    id: 11,
    title: 'Pancakes',
    description: 'Fluffy pancakes served with syrup and fresh fruit.',
    image: 'https://cdn.pixabay.com/photo/2016/10/05/06/14/pancakes-1725304_1280.jpg',
    vegetarian: true,
    vegan: false,
    lowCarb: false,
    glutenFree: false,
    lactoseFree: false,
    nutFree: true,
    soyFree: true,
    eggFree: false,
  },
  {
    id: 12,
    title: 'Quinoa Salad',
    description: 'A nutritious salad with quinoa, black beans, corn, and lime vinaigrette.',
    image: 'https://cdn.pixabay.com/photo/2018/01/25/16/22/quinoa-1953652_1280.jpg',
    vegetarian: true,
    vegan: true,
    lowCarb: false,
    glutenFree: true,
    lactoseFree: true,
    nutFree: true,
    soyFree: true,
    eggFree: true,
  },
  {
    id: 13,
    title: 'Beef Tacos',
    description: 'Delicious ground beef tacos topped with lettuce and cheese.',
    image: 'https://cdn.pixabay.com/photo/2016/09/18/14/43/taco-1586007_1280.jpg',
    vegetarian: false,
    vegan: false,
    lowCarb: false,
    glutenFree: false,
    lactoseFree: false,
    nutFree: true,
    soyFree: true,
    eggFree: false,
  },
  {
    id: 14,
    title: 'Baked Salmon',
    description: 'Tender salmon fillets baked with lemon and herbs.',
    image: 'https://cdn.pixabay.com/photo/2016/03/08/19/34/salmon-1247329_1280.jpg',
    vegetarian: false,
    vegan: false,
    lowCarb: true,
    glutenFree: true,
    lactoseFree: true,
    nutFree: true,
    soyFree: true,
    eggFree: true,
  },
  {
    id: 15,
    title: 'Chickpea Salad',
    description: 'A refreshing salad with chickpeas, cucumber, and a lemon dressing.',
    image: 'https://cdn.pixabay.com/photo/2019/01/28/07/08/salad-3961571_1280.jpg',
    vegetarian: true,
    vegan: true,
    lowCarb: false,
    glutenFree: true,
    lactoseFree: true,
    nutFree: true,
    soyFree: true,
    eggFree: true,
  },
  {
    id: 16,
    title: 'Mushroom Risotto',
    description: 'Creamy arborio rice cooked with mushrooms and Parmesan cheese.',
    image: 'https://cdn.pixabay.com/photo/2016/10/10/00/40/mushroom-1722850_1280.jpg',
    vegetarian: true,
    vegan: false,
    lowCarb: false,
    glutenFree: false,
    lactoseFree: false,
    nutFree: true,
    soyFree: true,
    eggFree: false,
  },
  {
    id: 17,
    title: 'Eggplant Parmesan',
    description: 'Breaded eggplant baked with marinara sauce and mozzarella cheese.',
    image: 'https://cdn.pixabay.com/photo/2016/01/28/21/39/eggplant-1166174_1280.jpg',
    vegetarian: true,
    vegan: false,
    lowCarb: false,
    glutenFree: false,
    lactoseFree: false,
    nutFree: true,
    soyFree: true,
    eggFree: false,
  },
  {
    id: 18,
    title: 'Tuna Salad',
    description: 'Flaky tuna mixed with mayo, celery, and served on a bed of greens.',
    image: 'https://cdn.pixabay.com/photo/2017/12/09/11/54/tuna-3018268_1280.jpg',
    vegetarian: false,
    vegan: false,
    lowCarb: true,
    glutenFree: true,
    lactoseFree: true,
    nutFree: true,
    soyFree: true,
    eggFree: true,
  },
  {
    id: 19,
    title: 'Fruit Smoothie',
    description: 'A refreshing mix of fruits blended with yogurt or juice.',
    image: 'https://cdn.pixabay.com/photo/2016/04/19/18/52/smoothie-1332056_1280.jpg',
    vegetarian: true,
    vegan: false,
    lowCarb: false,
    glutenFree: true,
    lactoseFree: false,
    nutFree: true,
    soyFree: true,
    eggFree: true,
  },
  {
    id: 20,
    title: 'Stuffed Bell Peppers',
    description: 'Bell peppers filled with a mixture of rice, beans, and cheese.',
    image: 'https://cdn.pixabay.com/photo/2015/08/03/05/32/food-837990_1280.jpg',
    vegetarian: true,
    vegan: false,
    lowCarb: false,
    glutenFree: true,
    lactoseFree: false,
    nutFree: true,
    soyFree: true,
    eggFree: true,
  },
  {
    id: 21,
    title: 'Pumpkin Soup',
    description: 'A creamy soup made with fresh pumpkin and spices.',
    image: 'https://cdn.pixabay.com/photo/2020/10/31/22/47/pumpkin-soup-5121981_1280.jpg',
    vegetarian: true,
    vegan: true,
    lowCarb: false,
    glutenFree: true,
    lactoseFree: true,
    nutFree: true,
    soyFree: true,
    eggFree: true,
  },
  {
    id: 22,
    title: 'Beef and Broccoli',
    description: 'Tender beef stir-fried with broccoli and soy sauce.',
    image: 'https://cdn.pixabay.com/photo/2019/02/15/14/09/beef-and-broccoli-3190807_1280.jpg',
    vegetarian: false,
    vegan: false,
    lowCarb: true,
    glutenFree: false,
    lactoseFree: true,
    nutFree: true,
    soyFree: false,
    eggFree: true,
  },
  {
    id: 23,
    title: 'BBQ Chicken',
    description: 'Grilled chicken thighs slathered in barbecue sauce.',
    image: 'https://cdn.pixabay.com/photo/2020/01/11/23/51/chicken-4765515_1280.jpg',
    vegetarian: false,
    vegan: false,
    lowCarb: true,
    glutenFree: true,
    lactoseFree: true,
    nutFree: true,
    soyFree: true,
    eggFree: true,
  },
  {
    id: 24,
    title: 'Carrot Cake',
    description: 'Moist carrot cake topped with cream cheese frosting.',
    image: 'https://cdn.pixabay.com/photo/2015/09/30/16/21/cake-981426_1280.jpg',
    vegetarian: true,
    vegan: false,
    lowCarb: false,
    glutenFree: false,
    lactoseFree: false,
    nutFree: false,
    soyFree: true,
    eggFree: false,
  },
  {
    id: 25,
    title: 'Falafel Wrap',
    description: 'Crispy falafel served in a wrap with salad and tahini.',
    image: 'https://cdn.pixabay.com/photo/2016/10/20/11/48/falafel-975852_1280.jpg',
    vegetarian: true,
    vegan: true,
    lowCarb: false,
    glutenFree: false,
    lactoseFree: true,
    nutFree: false,
    soyFree: true,
    eggFree: true,
  },
  {
    id: 26,
    title: 'Coconut Curry',
    description: 'A tropical coconut curry made with seasonal vegetables.',
    image: 'https://cdn.pixabay.com/photo/2017/05/08/20/41/curry-2291620_1280.jpg',
    vegetarian: true,
    vegan: true,
    lowCarb: false,
    glutenFree: true,
    lactoseFree: true,
    nutFree: true,
    soyFree: true,
    eggFree: true,
  },
  {
    id: 27,